### ISSUE TITLE
Bug in setup.py (with fix): some pkg-config failures are ignored.

### ISSUE THREAD

**Issue by jeffstearns** [libfuse/pyfuse3#11]
setup.py has some bugs in the way it calls pkg-config.

When pkg-config fails, setup.py raises SystemExit() but doesn't supply a nonzero status code.

The error exists on lines 167 and 183 of setup.py.  The offending lines look like this:
       `raise SystemExit() # pkg-config generates error message already`

Fix:
      `raise SystemExit(1) # pkg-config generates error message already`

**Comment by Nikratio** [comment]
Thanks for the report!
