### ISSUE TITLE
pyfuse3 installation abruptly interrupted

### ISSUE THREAD

**Issue by adjakka** [libfuse/pyfuse3#12]
Collecting pyfuse3
  Using cached https://files.pythonhosted.org/packages/f1/92/8fef06a82c69096511c9877c8f5750f06650b70dc937a78cc75ab3e27b15/pyfuse3-1.1.tar.gz
Files/directories not found in /tmp/pip-install-q62tt1bn/pyfuse3/pip-egg-info

Has anyone faced this?

**Comment by Nikratio** [comment]
Thanks for the report! I'm going to close this since this is (if anything) a problem with PyPi or pip rather than pyfuse3, so even if people respond here there is no clear action that we can take in pyfuse3. Hope you understand!
