### ISSUE TITLE
EPERM should be EACCES in a few places

### ISSUE THREAD

**Issue by rgbyrnes** [libfuse/pyfuse3#22]
In `src/handlers.pxi`, if the `access` handler returns a false boolean value, then `FUSEError(EPERM)` is raised ... shouldn't that be `EACCES`?

The examples `examples/hello.py` and `examples/hello_asyncio.py` raise `FUSEError(EPERM)` if write access is denied for `open` ... I think that should also be `EACCES`.

The tests `test/test_examples.py` and `test/test_fs.py` have the same problem for `open`.

**Comment by Nikratio** [comment]
When you say "problem", could you elaborate what the actual problem is? What are the negative consequences of returning EPERM instead of EACCES?

**Comment by rgbyrnes** [comment]
`EPERM` is nonstandard: see the manpages for [access ](url)and open, which

**Comment by rgbyrnes** [comment]
Sorry about the last truncated comment ... let me try that again.

`EPERM` is nonstandard: the manpages for [access](https://pubs.opengroup.org/onlinepubs/9699919799/functions/access.html) and [open](https://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html) don't mention `EPERM` at all, and both say that `EACCES` should be returned instead.

**Comment by Nikratio** [comment]
Thanks for adding the reference! If someone provides a pull request to fix this, I'd be happy to merge.

**Comment by ThomasWaldmann** [comment]
fixed by #28. close?

**Comment by rgbyrnes** [comment]
That looks great to me ... thanks!  (And sorry that I never got around to submitting a PR.)
