### ISSUE TITLE
Attribute Caching Question

### ISSUE THREAD

**Issue by jdp5** [libfuse/pyfuse3#23]
Hi:

I have been using the passthroughfs.py example, and I am seeing something weird happen with attributes.  Specifically, if I create a file in the underlying file system, I get the correct attributes the first time I stat the file or list the directory contents in the FUSE mount.  Some of the attributes are not updating when files are modified in the underlying file system, then I look at them in the FUSE mount.  entry_timeout and attr_timeout are set to 0 in the returned entry in _getattr, so I don't think any caching should happen.

I've added a debug statement to print st_size from the EntryAttributes variable that is created in _getattr, and it is correctly set in the entry (and st_blocks is set based on it, which does change).  However, the size is not correct when I stat the file in the FUSE mount.  I have also noticed timestamps not updating, but hard links and mode updates come through.

This is what I see when running the following commands (a is source directory, b is FUSE mount):

```
> echo a > a/a
> stat b/a
  File: b/a
  Size: 2         	Blocks: 1          IO Block: 512    regular file
Device: 36h/54d	Inode: 1814195     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-03-26 22:26:32.322392232 +0000
Modify: 2020-03-26 22:24:29.742113292 +0000
Change: 2020-03-26 22:24:29.742113292 +0000
 Birth: -
> yes a | head -c 10000 >> a/a
> stat b/a
  File: b/a
  Size: 2         	Blocks: 20         IO Block: 512    regular file
Device: 36h/54d	Inode: 1814195     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-03-26 22:26:32.322392232 +0000
Modify: 2020-03-26 22:24:29.742113292 +0000
Change: 2020-03-26 22:24:29.742113292 +0000
 Birth: -
> ln a/a a/a2
> stat b/a
  File: b/a
  Size: 2         	Blocks: 20         IO Block: 512    regular file
Device: 36h/54d	Inode: 1814195     Links: 2
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-03-26 22:26:32.322392232 +0000
Modify: 2020-03-26 22:24:29.742113292 +0000
Change: 2020-03-26 22:24:29.742113292 +0000
 Birth: -
> chmod 600 a/a
> stat b/a
  File: b/a
  Size: 2         	Blocks: 20         IO Block: 512    regular file
Device: 36h/54d	Inode: 1814195     Links: 2
Access: (0600/-rw-------)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-03-26 22:26:32.322392232 +0000
Modify: 2020-03-26 22:24:29.742113292 +0000
Change: 2020-03-26 22:24:29.742113292 +0000
 Birth: -
> stat a/a
  File: a/a
  Size: 10002     	Blocks: 24         IO Block: 4096   regular file
Device: 801h/2049d	Inode: 1814195     Links: 2
Access: (0600/-rw-------)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2020-03-26 22:26:32.322392232 +0000
Modify: 2020-03-26 22:27:48.690696428 +0000
Change: 2020-03-26 22:29:16.171019526 +0000
 Birth: -
```

**Comment by Nikratio** [comment]
Thanks for your interest in pyfuse! As far as I can tell, this is a question about how to use pyfuse3 rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

As far your question: have you disabled writeback caching? I believe writeback caching can't work unless some attributes are cached, so this may override your 0 timeouts.

Thanks!
