### ISSUE TITLE
Python3.9 : Regenerate pyfuse3.c  by cython

### ISSUE THREAD

**Issue by HJarausch** [libfuse/pyfuse3#26]
The PyTypeObject structure has changed. There is no tp_print slot any more.
I couldn't regenerate it myself, since cython bails out with "GIL" errors.
Thanks,
Helmut

**Comment by Nikratio** [comment]
Will do so once Python 3.9 is released - it might well be that current stable Cython does not support it yet.

**Comment by ThomasWaldmann** [comment]
It was deprecated in 3.8 and now they finally removed it in 3.9, breaking stuff (pyfuse3 and also llfuse).

**Comment by ThomasWaldmann** [comment]
BTW, it would be nice if one could optionally cythonize this at install time. Maybe triggered by some env var?

This can avoid situations like this (and even worse situations like the one now present in llfuse and in every sw using llfuse).

**Comment by ThomasWaldmann** [comment]
The tp_print issue should be fixed since quite a while in cython 0.29.xx, so just try the latest release.

**Comment by Nikratio** [comment]
You can't Cythonize at install time - at that point the code has already been compiled. But if you have Cython installed, you can run `setup.py build_cython` before `setup.py build`.

**Comment by ThomasWaldmann** [comment]
With "at install time", I mean when llfuse is pulled in as a dependency, e.g. by extras_require.
Or when installed using `pip install llfuse`.

**Comment by Nikratio** [comment]
If there's a way to do that that doesn't break other use-cases, then I'll happily accept a pull request :-).

**Comment by Nikratio** [comment]
done
