### ISSUE TITLE
pyfuse3 tests fail with pytest>=6.0.0

### ISSUE THREAD

**Issue by mucamaca** [libfuse/pyfuse3#27]
All tests fail with AttributeError because `catch_log_handler` was removed in [a pytest pull request](https://github.com/pytest-dev/pytest/pull/7224) prior to their 6.0.0 release.

[output of `python3 -m pytest test/`](https://paste.sr.ht/~turminal/65ac74f632ef14dd82a9a3bf255876a5b965cada) with pyfuse 3.1.1 and pytest 6.1.0

**Comment by ThomasWaldmann** [comment]
from changelog:

The item.catch_log_handler and item.catch_log_handlers attributes, set by the logging plugin and never meant to be public, are no longer available.

The deprecated --no-print-logs option and log_print ini option are removed. Use --show-capture instead.

**Comment by ThomasWaldmann** [comment]
@Nikratio Thanks for fixing! Are you working on a llfuse port of this change, or shall I try?
