### ISSUE TITLE
st_{m,a,c,...}time_ns methods lose accuracy

### ISSUE THREAD

**Issue by Grunthos** [libfuse/pyfuse3#34]
Python real values have 15 (or so) digits of accuracy. Seconds-since-1970 (eg. 1,576,800,000), use 10 of those digits (roughly). This means that representing any FS time as a real value will lose several decimal places.

Specifically, it will not have sufficient precision to represent seconds with nano-second accuracy.

This affects (I think) all of the uses of the st_{m,a,c,...}time_ns methods.

Worse, it affects the getters (eg. st_mtime_ns), causing them to return values that are exactly 1 second greater than they should be.

**Comment by Grunthos** [comment]
I am totally unfamiliar with the code, but I suspect that the only solution may be to remove all attempts to represent the nanosecond values as real/float/double values, and *if desirable for some reason* replace those values with "_**m**s" (millisecond) versions.

**Comment by Grunthos** [comment]
Another interesting option: python3 has unlimited INT values, the **_ns** functions could return integers...

**Comment by Grunthos** [comment]
FWIW, there's a pull request that fixes the rounding errors. I suspect my earlier ramblings are largely irrelevant, and reflect a slow learning curve!

**Comment by ThomasWaldmann** [comment]
PR: #35

**Comment by Grunthos** [comment]
Fixed as above.
