### ISSUE TITLE
be compatible with macOS?

### ISSUE THREAD

**Issue by tigerking** [libfuse/pyfuse3#44]
python 3.7
pip install pyfuse3

Lots of error and install failed.
Search and google , it seems that pyfuse3 does not support Mac OS. Is that true? Do we have plan to support Mac OS?

**Comment by Nikratio** [comment]
pyfuse3 supports any system that's supported by libfuse3 (or has a compatible interface). So as soon as that exists for MacOS, pyfuse3 will support it.
