### ISSUE TITLE
Gracefully stopping pyfuse3 from within an application

### ISSUE THREAD

**Issue by JustAnotherArchivist** [libfuse/pyfuse3#9]
Is there any way to cleanly stop a mount from within a module using pyfuse3? E.g.

    import pyfuse3

    class MyOperations(pyfuse3.Operations):
        # ...

    async def dosomework():
        await trio.sleep(3)
        pyfuse3.close() # <<< What to put here to stop the mount?

    await main():
        async with trio.open_nursery() as nursery:
            nursery.start_soon(pyfuse3.main)
            nursery.start_soon(dosomework)

    # set up operations, pyfuse3.init
    trio.run(main)

I would expect this to stop the mount after ~3 seconds, but it definitely doesn't work. During my tests with #8, I even managed to get a segfault, but that might've been related to my changes instead.
I guess it should be possible to execute `fusermount -u`, but that seems very awkward.

**Comment by JustAnotherArchivist** [comment]
> It's a bit unusual for a filesystem to unmount itself :-)

Well, for a traditional filesystem, that's probably correct. But it makes perfect sense for a FUSE-based filesystem, especially if it's not just a proxy for e.g. some remote files. The implementation might detect an inconsistent state of the FS and want to remount it, for example. I believe that it's impossible to do that from the outside.
There could also be a way of controlling how the FS works, for example by writing to a special file within the FS or through a socket. This could include a `quit`-type command for clean shutdown. And that might even be available to users that can't run `fusermount -u`.

> libfuse has fuse_session_exit, which we could expose for this. However, this will only result in termination once the next request comes in, since we're blocking in trio.

Right, I actually experimented a bit with that earlier and ran into exactly that issue.

I guess `wait_fuse_readable` would have to be cancellable. With asyncio, a `Future` is needed anyway, so that can just be stored somewhere and cancelled from another ethod. For Trio, it seems that [`trio.hazmat.notify_fd_close`](https://trio.readthedocs.io/en/latest/reference-hazmat.html#trio.hazmat.notify_fd_close) on the session file descriptor should work. This would trigger a `ClosedResourceError` in `wait_fuse_readable`.

**Comment by JustAnotherArchivist** [comment]
How does adding a coroutine `pyfuse3.shutdown` (or similar name) sound? This method would call `fuse_session_exit`, cancel the FD readability future/notify Trio of the FD closure, and wait until all workers terminate (or rather, until `pyfuse3.main` terminates). Maybe it should also call `pyfuse3.close` at the end, but I'm not sure; FWIW, I can't think of any scenario where *not* calling `close` after the above would make sense right now.

**Comment by JustAnotherArchivist** [comment]
My idea was that the calling method would likely want to wait for the shutdown to complete. But you're right, it's not necessary. Since both `pyfuse3.main` and the application's code is already running asynchronously anyway, a thin wrapper around `pyfuse3.main` in the application code triggering an event would serve the same purpose.

In that case though, the name of the method should make it clear that the shutdown happens asynchronously. `initiate_shutdown` maybe?

**Comment by Nikratio** [comment]
Sounds good to me! Would you be able to provide a pull request? :-).
