### ISSUE TITLE
move docs to readthedocs

### ISSUE THREAD

**Issue by ThomasWaldmann** [libfuse/pyfuse3#90]
see: https://pyfuse3.readthedocs.io/en/latest/

**Comment by ThomasWaldmann** [comment]
@Nikratio need to add you as maintainer for this on rtd also (need rtd email or username).

**Comment by ThomasWaldmann** [comment]
TODO: change docs link in readme (points to rath.org, but i can't update docs there when i do a release - rtd docs should auto-update via webhook / gh integration).

**Comment by ThomasWaldmann** [comment]
@Nikratio someone needs to fix the readthedocs integration on the github settings side, I do not have the permissions to do that.

**Comment by Nikratio** [comment]
Thanks for tackling this! Can you tell me exactly what to do?

**Comment by ThomasWaldmann** [comment]
https://readthedocs.org/dashboard/pyfuse3/integrations/ go there, delete any existing github webhook and add a new one (guess likely you also need to be logged in into github).

**Comment by Nikratio** [comment]
Done.

**Comment by ThomasWaldmann** [comment]
OK, merging PR #92 will complete this.
